### PR TITLE
V4.9.0

### PR DESCRIPTION
**Pull request by NekR**
## Version `4.9.0` is on the way! 🎉 

All tests are finally passing and I'm almost ready to merge this and make a release.

The changes (if I remember correctly, I still have to make a review of them):

* We now have in-browser tests! 🎉 (with puppeteer)
* Added support of Navigation Preload feature (ServiceWorker's navigation preload, more in docs soon)
* Added `appShell` option which is mean to replace `ServiceWorker.navigateFallbackURL` and `AppCache.FALLBACK`. It's an encapsulation which handles both. It uses `cacheMaps` feature for ServiceWorker.
* I plan to deprecate `ServiceWorker.navigateFallbackURL`
* `ServiceWorker.navigateFallbackForRedirects` is now `false` by default. It was `true` and it may be seen as a breaking change, I kinda see it so. Though, it might be also considered as a bug. I need feedback for this.

Merging soon!  🎉 😱

### CODE REVIEW

**Comment by GGAlanSmithee** [comment]
Great work as always @NekR 

> ServiceWorker.navigateFallbackForRedirects is now false by default. It was true and it may be seen as a breaking change,

According to [semver](https://semver.org/) (if we follow this convention) it is indeede a major version change;

> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API.

You requested a review. Are you intereseted in a code review for this PR?

**Comment by NekR** [comment]
@GGAlanSmithee well, I didn't expect a code review, that's why I wrote browser tests -- to make sure I didn't break anything. Everyone is busy, and that's okay :-) I requested a review to discuss the things, probably just a mention would be better.

Yeah, I think I agree. We can revert that change an just mark navigateFallbsckURL as a deprecated feature, and ask to migrate to appShell option.

**Comment by GGAlanSmithee** [comment]
> Everyone is busy, and that's okay :-)

yes, too busy 🏃 :)

> We can revert that change an just mark navigateFallbsckURL as a deprecated feature, and ask to migrate to appShell option.

Sounds like a good option!

**Comment by NekR** [comment]
Released! https://github.com/NekR/offline-plugin/releases/tag/v4.9.0

**Pull request merged**
