### PR TITLE
add disableInstall

### PR DESCRIPTION
**Pull request by zamboney**

### CODE REVIEW

**Comment by NekR** [comment]
I see your intention here, but that `iframe` request is actually done only first time when AppCache didn't cache anything yet. Once AppCache is installed, that `iframe` page is also cached in it (master page), so network request is done only once.

**Comment by zamboney** [comment]
This is true when the page route isn't change
When the route change the are requests to get the app cache file. Only when the request is 404 its get the file from the cache

**Comment by NekR** [comment]
@zamboney AppCache doesn't work that way. iframe's .html file is the master entry and it's always cached and returned from cache whatever way you request it and dynamic routes doesn't affect that.

Do you mean that when you use iframe dynamic routes such as `/about?what=ever` aren't cached? Without iframe (using `manifest` attribute on those page) they indeed are cached because they became master entries, but that isn't good idea because AppCache has storage limit 
and putting every route to will case the quote to exceed. Also on AppCache update, browser will be downloading all those pages, say 100 of them, which is absolutely bad for users' traffic.

**Comment by zamboney** [comment]
there are been cache but it's still make a request to get the data. only when offline it's go to the cache storage and get the data from there.

i tested it on *fiddler* and there were a request to the server when there *was* an internet connection. when there *wasn't* an internet connection the file that was on the app cache get from the offline cache storage.

my solution get the file from the storage even if the *was* an internet connection

**Comment by NekR** [comment]
I don't get it. How file from AppCache can be loaded from network? And what exact file you mean? Because I don't follow. Please provide an example of AppCache which has described behavior and explicitly to the file in AppCache which is loaded from the network instead from the cache.

**Comment by zamboney** [comment]
i'm using angular2 and when i'm on the base route there is no request to to server and when i'm route to nested route or dynamic route there is a request to server...

i fork `angular2-webpack-starter`

clone https://github.com/zamboney/angular2-webpack-starter

run `npm install && npm run webpack-dev-server` 

open fiddler or any other sniffer

then do to `about` or `home`  and press reload a couple of time

you will see that the js files is been loaded from the server

Capture

**Comment by NekR** [comment]
@zamboney Okay, I'll check it out. Thanks for the example! I hope to resolve this issue.

**Comment by zamboney** [comment]
i resolve it by putting an absolute path on the manifest html attribute... also i don't know how you can resolve it because the iframe dynamically loading in after the javascripts files.

maybe you could accept my pull request until you figure out the solution yourself...

**Comment by NekR** [comment]
> also i don't know how you can resolve it because the iframe dynamically loading in after the javascripts files.

That doesn't affect anything when AppCache is already installed. 

> maybe you could accept my pull request until you figure out the solution yourself...

I don't tend to introduce features without deeply thinking about it. This applies too all features: which I implement and from other people.

@zamboney btw, have you tried to set publicPath to offline-plugin? e.g this:

```js
  new OfflinePlugin({
    relativePaths: false,
    publicPath: '/'
  })
```

**Comment by zamboney** [comment]
nope it didn't work

**Comment by NekR** [comment]
Well, i just checked it. So instead of doing what you are proposing here you can just list all needed routers in cache. This will be better and preload them alongside with otherwise. In you solution it loads those routes only when you navigate to them. Plus listening all routes will add them to the ServiceWorker cache too, while in you solution it won't.

Here is code example:

```js
new OfflinePlugin({
  caches: { main: [':rest:', '/home'] },
  externals: ['/home']
})
```

**Comment by zamboney** [comment]
It could be that easy if I had a countable routes. Instead I have a generated route like nested route base on id like 'item/:Id'
So I can't really register all my route in advance

**Comment by NekR** [comment]
I see. But this option doesn't help you with SW.

Btw, why do you need to cache all routes in your app?

**Comment by NekR** [comment]
Okay, I merged this. I re-thought all the things here and now I think that it makes sense. After all, this option won't hurt.

**Pull request merged**
