### PR TITLE
fixes hasSW function if ServiceWorker is disabled

### LINKED ISSUE #393: Disabeling ServiceWorker is not possible anymore
The [docs](https://github.com/NekR/offline-plugin/blob/master/docs/options.md#serviceworker-object--null--false) state that you could set `ServiceWorker` to `null` or `false` to disable it.

Since 39acf1f6f70c48e02589f52d7bbe9466a924bf3d this does not work anymore. The check if `ServiceWorker.force` is true breaks if `ServiceWorker` is null or false:
https://github.com/NekR/offline-plugin/blame/master/tpls/runtime-template.js#L4

PR #388 fixes this issue.

### PR DESCRIPTION
**Pull request by mojoaxel**
This fixes a bug I had after updating to 5.0.5. 
I dont't use ServiceWorkers so I disabled them with `ServiceWorker: false`. 

fixes #393

### CODE REVIEW

**Comment by NekR** [comment]
Sorry for a delay and thanks for spotting the issue and making a PR! 💪👍

**Comment by mojoaxel** [comment]
Thx! A new release would be great!

**Comment by ncapdevi** [comment]
There still hasn't been a release for this, correct?

**Comment by mojoaxel** [comment]
@ncapdevi Sadly no..
@NekR Can you please make a release!

**Comment by NekR** [comment]
@mojoaxel @ncapdevi Sorry guys, I forgot about it. Made a release now. Thanks for reminding me!

**Comment by ncapdevi** [comment]
@NekR Thanks!

**Pull request merged**
