### PR TITLE
Added a FAQ entry on disabling/preventing console logging.

### PR DESCRIPTION
**Pull request by begincalendar**
Refer to [this](https://github.com/NekR/offline-plugin/issues/143#issuecomment-265417832) issue.

I may have misinterpreted how this option works.

If so, please let me know.

### CODE REVIEW

**Comment by NekR** [comment]
@begincalendar Many thanks for doing this 👍 💯

**Comment by NekR** [comment]
@begincalendar if something (you are too busy or not comfortable with doing it), let me know and I'll do that changes myself. No problem at all!

**Comment by begincalendar** [comment]
@NekR You're most welcome, it's the least I can do. Thank you for your work on this plugin.

I have updated the changes.

**Comment by NekR** [comment]
@begincalendar oh, you removed some of you code which I didn't mean to remove (and you removed old commit too unfortunately :-( ). Okay, I'll merge it and try to recover some of your text by memory.

Thanks for contributing, that's really great that you're helping with it 😎

**Pull request merged**
