### PR TITLE
Fix runtime template using es5 function style

### PR DESCRIPTION
**Pull request by diondirza**
Using latest release of this plugin has thrown some error in some browser that doesn't support es6 syntax, need to change this line bro.

### CODE REVIEW

**Comment by NekR** [comment]
Indeed. Can you fix the tests? Then I'll be able to merge.

**Comment by diondirza** [comment]
Forgot about the test, will working on it.

**Comment by diondirza** [comment]
Am I doing it right for fix the test fixtures? specially on case `paths-explicit-absolute-tools-override-outside`. I just copy paste the hash value from output to expected value there.

**Comment by NekR** [comment]
Yeah, you are doing it right. Thank you for the PR, I'll merge as soon as I'm back to my computer.

**Comment by diondirza** [comment]
no problem  bro.

**Comment by NekR** [comment]
@diondirza oh, I just realized that. You made PR against `master` but it had to be done against `v4` branch :-(

**Comment by NekR** [comment]
I did the fix manually, I was a bit critical I guess. Anyway, thank you very much for creating this and pointing me to this problem. Very appreciated!

`4.6.1` is out with the fix, btw

**Comment by diondirza** [comment]
no problem, I was gonna change the pull request when I got home. Sorry for late response bro.. Anyway good job!

**Pull request closed without merging**
