### PR TITLE
Adding new parameter `cdnPath`

### PR DESCRIPTION
**Pull request by domderen**
Specifying this parameter prepends the CDN Path to the resources generated by Webpack.

### CODE REVIEW

**Comment by domderen** [comment]
@NekR I had a look there, and didn't really find similar functionality, but please let me know if there is a way to achieve the same thing with what's already there.

**Comment by NekR** [comment]
> I had a look there, and didn't really find similar functionality, but please let me know if there is a way to achieve the same thing with what's already there.

I meant the functionality you implemented first. Nevermind.

Okay, first of all, you have to do PR against `v4` branch because master contains `v3` (stable). I know it isn't really obvious :-(

`cdnPath` sounds good, but I think the idea of `publicPath` in webpack itself actually meant to be a CDN path.  In `v4` you can use `publicPath` as a CDN path, e.g. by setting it to `https://cdn.example.com/` and setting `location` property of `ServiceWorker` to `https://example.com/sw.js`, but I guess `cdnPath` is better.

It would be good to hear some of your use cases and why decided that `cdnPath` is required. Also, do you use `HtmlWebpackPlugin` with it or `index.html` is built separately?

**Comment by domderen** [comment]
Oh, sorry didn't realize there is `v4` branch. Will have a look there, to see if that is portable there.

And yeah, I user `publicPath` as my CDN address in Webpack. But I couldn't use it like that on this branch. Hence the PR. 

One thing that I also had to customize, that might not be handled in `v4` is an index.html asset. Or more explicitly the `/` asset. This one cannot really be served from CDN, and so cannot be added in the `sw.js` as `https://cdn.example.com/` but rather as `/`, because no-one will try to access the index.html from the CDN. I added that in [here](https://github.com/NekR/offline-plugin/pull/91/files#diff-1fdf421c05c1140f6d71444ea2b27638R489).

I am using `HtmlWebpackPlugin`, but I didn't have to modify my `index` file template to support `offline-plugin` which was really nice ;)

**Comment by NekR** [comment]
@domderen sorry, I don't have much time right now to handle all this. I think I'll be able to discuss details of this implementation around next week.

**Comment by domderen** [comment]
No worries, I will actually close this PR, as I am experimenting with a different approach on branch `v4`. We can discuss it there, when you have some time ;)

**Pull request closed without merging**
