### PR TITLE
403 popup issuse

### PR DESCRIPTION
**Pull request by zamboney**
this is for 403 request popup message when there is one and a new version the browser begin an infinity loop
this solution fix it

### CODE REVIEW

**Comment by NekR** [comment]
Hi @zamboney, this sounds good. But what is the `request` in the `mapAssets()` function?

**Comment by zamboney** [comment]
it's for handling the request of the service worker when it's fetch that the version has been change

**Comment by NekR** [comment]
@zamboney Yes, I understand that. The problem is that there in no `request` in scope of `mapAssets()`. `request` in only available inside `fetch` event via `event.request`.

Also, why do you add AppCache disable options in this PR? If you want to add them, it's better to do in separate PR.

**Comment by NekR** [comment]
One more thing: while 403 infinite loop issue is a bug and can be applied to current version (`v3` in master), AppCache disable install is a feature and has to be added to next release, which is in `v4` branch.

**Comment by zamboney** [comment]
so you want me to open a new PR's

**Comment by NekR** [comment]
@zamboney for AppCache feature -- yes. We can also discuss it here before you open the PR. What is the purpose of that feature, why don't user `runtime.install()`?

**Comment by zamboney** [comment]
the reason is that when the page is reload on a dynamic route like `/about` or `/about?what=ever` there is a request to the server when the `iframe` request the manifest

our solution was to use the plugin for creating the manifest but consume it through the `html` tag. that why there was no requests to the server.

**Comment by zamboney** [comment]
https://github.com/NekR/offline-plugin/pull/95
https://github.com/NekR/offline-plugin/pull/96

**Pull request closed without merging**
