### PR TITLE
Fix runtime typings.

### PR DESCRIPTION
**Pull request by odensc**
Submodules (e.g. with a "/" in them) don't work with `declare module` in a foreign npm package. This PR fixes the that by renaming the typings file to `runtime.d.ts`, so it will be used when importing `offline-plugin/runtime`.

### CODE REVIEW

**Comment by NekR** [comment]
@odensc so with this change it works for you now, right?

**Comment by odensc** [comment]
Yes. :) Current version (`4.8.0`) did not work, but I can confirm it works with these changes.

**Comment by NekR** [comment]
Okay, I'll merge it. Btw, what version TypeScript you were using?
I don't use TypeScript for a while so I'm not able to test this versions as wasn't able to test previous one.

**Comment by odensc** [comment]
I was using the latest, `2.3.2`. Not sure if something changed since the original PR.

**Comment by NekR** [comment]
Okay, thank you for the PR! 👍

**Comment by NekR** [comment]
https://github.com/NekR/offline-plugin/releases/tag/v4.8.1

**Comment by odensc** [comment]
Great, thanks!

**Pull request merged**
