### PR TITLE
Added Open Collective backers and sponsors and call to donate after npm install

### PR DESCRIPTION
**Pull request by xdamman**

### CODE REVIEW

**Comment by NekR** [comment]
Is that post install thing mandatory?

**Comment by xdamman** [comment]
It's not, but preferred :-)
We would love to experiment with it, get users' feedback and see how it performs.
You can also remove the logo to make it much less prominent by removing the "logo" attribute in package.json.

**Comment by xdamman** [comment]
and you can also remove it entirely anytime if people complain. So I think it's worth trying. What do you think?

**Comment by NekR** [comment]
I think I don't want the banner at all. It's annoying. People didn't use the thing yet, but it already asks about money. Also if `offline-plugin` will be installed as a dependency, will the banner be shown?

**Comment by NekR** [comment]
Thanks for the PR! I'm going to format it a bit nicer, probably put bakers/sponsors to the top. But I'm going to disable the postinstall banner.

**Pull request merged**
