### PR TITLE
Allow service workers to be installed on 127.0.0.1

### LINKED ISSUE #187: Service Worker install 127.0.0.1
I was running my site on 127.0.0.1 instead of localhost which caused this check to fail
https://github.com/NekR/offline-plugin/blob/0fffb644f273612e0b83bb944dd9a3e00689f3b7/tpls/runtime-template.js#L8

Can service workers be installed when running locally at 127.0.0.1?

### PR DESCRIPTION
**Pull request by thomaswelton**
Fixes #187

### CODE REVIEW

**Comment by NekR** [comment]
All seems fine, thank you @thomaswelton!

**Comment by azzgo** [comment]
HI, @NekR , Have it is released? It seems not work on 4.6.2.

**Comment by NekR** [comment]
Hi @azzgo, I don't think it's, see: https://unpkg.com/offline-plugin@4.6.2/tpls/runtime-template.js
It was merged into master but v4 is in a separate branch for a while now.

**Comment by NekR** [comment]
@azzgo Okay, I merged this PR into v4. Once https://github.com/NekR/offline-plugin/pull/230 lands I'll be able to cut 4.7 release.

**Comment by azzgo** [comment]
cool, thanks for reply.

**Pull request merged**
