### PR TITLE
403 request popup message  infinity loop

### PR DESCRIPTION
**Pull request by zamboney**

### CODE REVIEW

**Comment by NekR** [comment]
Again, there is no `request` variable in scope of `mapAssets()` function. Did you mean to perform such operation inside `fetch` event handler?

**Comment by zamboney** [comment]
The request is in the args of the function. I don't understand why you say there isn't one

**Comment by NekR** [comment]
There is a `result`, not a `request`.

**Comment by zamboney** [comment]
i understand... so you think i should change it to `Fetch`

**Comment by NekR** [comment]
I'm not yet sure where exactly it should be, but yes, somewhere in `fetch` event. I'll think about it.

**Comment by zamboney** [comment]
10x!

**Comment by zamboney** [comment]
is there any progress...?

**Comment by NekR** [comment]
Nope. Not yet.

**Comment by NekR** [comment]
I'll handle this for `v4`, probably in September.

**Comment by NekR** [comment]
@zamboney do you know how I may easily reproduce this issue? Do you have some demo/repo which could demonstrate this?

**Comment by NekR** [comment]
Closing this is I don't understand what happens here and why that doesn't work by default + it was added in a wrong place in the code.

If you have a test case/repo with a project to reproduce the problem, then feel free to open an issue about it and provide a test case.

**Pull request closed without merging**
