### PR TITLE
Updating docs according to bug #401

### PR DESCRIPTION
**Pull request by matheusml**
#401

### CODE REVIEW

**Comment by GGAlanSmithee** [comment]
@matheusml 👍 missed this in #402

**Comment by matheusml** [comment]
@GGAlanSmithee there's something wrong with Travis 👎

**Comment by GGAlanSmithee** [comment]
@matheusml yes, it's unrelated to your PR :)

**Comment by GGAlanSmithee** [comment]
Maybe this check could be added internally inside the dynamically generated `install` function @NekR ?

**Comment by NekR** [comment]
> Maybe this check could be added internally inside the dynamically generated install function @NekR ?

It's there. Chrome on iPhone doesn't support ServiceWorker so problem is in something else. Because it case of that code, `install()` is never executed. It might be AppCache problem there.

**Comment by GGAlanSmithee** [comment]
Ah ok, @NekR, then I should probably revert [this](https://github.com/NekR/offline-plugin/pull/402/files#diff-2ff67fee0173608876ccc012bf3ff6ceR57), right?

**Comment by GGAlanSmithee** [comment]
@matheusml is the light of @NekR's last comment, can you specify what device / platform you get this error on, and also if it's a consistent error across all environments? Thanks.

**Comment by GGAlanSmithee** [comment]
disregard, just saw the conversation in #401 :) closing this since it's not the issue

**Pull request closed without merging**
