### PR TITLE
add faq and troubleshooting entry regarding insecure response

### PR DESCRIPTION
**Pull request by GGAlanSmithee**
Regarding #296 

Not sure if I interpreted the issues corectly. Added to both FAQ and troubleshooting, since it's not really clear where it should be. Let me know if you want anything changed @NekR

### CODE REVIEW

**Comment by NekR** [comment]
Hey! I believe I meant only troubleshooting part, but I'm totally fine with having `relativePaths` explanation in FAQ 👍 

About troubleshooting section. I think we need to say something about that serviceworker/appcache files might be generated into a wrong directly. I know it's partially implied by "see FAQ about `relativePaths`" but would be good to make it clearer. E.g. "also make sure that ServiceWorker and/or AppCache files are generated into a right folder. You may use `ServiceWorker.output` and `AppCache.output` to change output of the files. See options for details."

Also can you rename `serviceworker.js` to `sw.js` since `sw.js` is the default naming. Just to not confuse people.

@GGAlanSmithee Great work as always! Your help is very appreciated. Thanks! 👌 👏

**Comment by NekR** [comment]
Oh, also, any idea why tests are failing with this simple docs PR? Looks like AppVeyor issue/glitch.

**Comment by GGAlanSmithee** [comment]
@NekR thanks for the excellent feedback I will fix it tomorrow if I find time :) also, I will try to make more contributions :+1:

**Comment by NekR** [comment]
Added you to 4.9.0 release notes: https://github.com/NekR/offline-plugin/releases/tag/v4.9.0

Sorry I forgot to do so initially :-(

**Comment by GGAlanSmithee** [comment]
@NekR fixed your comment - sorry for the delay!

> Added you to 4.9.0 release notes: https://github.com/NekR/offline-plugin/releases/tag/v4.9.0

Thanks! Very kind of you. 🙇

**Comment by GGAlanSmithee** [comment]
Have merged latest master into this. Will merge since you've OK:ed it before @NekR. The problem with the CI will be resolved when #436 is merged, will wait until then.

**Pull request merged**
