### PR TITLE
add scope registration test

### PR DESCRIPTION
**Pull request by GGAlanSmithee**
I wanted to write some tests for #439 but couldn't find a good way to doit, so instead I added a general test to make sure the scope is set when registering a SW in browser with a scope.

### CODE REVIEW

**Comment by GGAlanSmithee** [comment]
@lilfolr CC:ing you since you authored #439. Not sure if you have any interest in / input on this, but if you do, feel free to share it :)

**Comment by lilfolr** [comment]
Yeah, definitely interested.
I'll have a look on Sunday :)

**Comment by NekR** [comment]
I want to merge this, but I believe `scope` is always present of the registration, even if it wasn't passed via params. Browser figures out the scope on its own and then uses it.

**Comment by NekR** [comment]
Oh, nevermind. I misunderstood what it does. Merging. Thanks @GGAlanSmithee ❤️

**Comment by GGAlanSmithee** [comment]
Thank you @NekR 💯

**Pull request merged**
