### PR TITLE
dynamic publicPath option during runtime install

### PR DESCRIPTION
**Pull request by Bobgy**
this is a prototype for dynamic publicPath.
I got it working for my use case, but it may not work together with other options.

and for FYI, my usage of OfflinePlugin looks like
```js
new OfflinePlugin({
    ServiceWorker: {
        output: '../sw.js',
        scope: '/',
        events: true,
        entry: path.resolve('./.../.../entry.js'), // my entry file
    },
    autoUpdate: false,
    responseStrategy: 'cache-first',
    version: '',
    caches: 'all',
})
```

add feature #184

### CODE REVIEW

**Comment by Bobgy** [comment]
holy crap, accidentally saw this, https://stackoverflow.com/questions/38835273/when-does-code-in-a-service-worker-outside-of-an-event-handler-run
I think my implementation is wrong, going to revise on it

**Comment by Bobgy** [comment]
this version works for me, but the configuration around publicPath seems really complicated to me, I cannot really add my option to other possible configs

**Comment by Bobgy** [comment]
need some help on that

**Comment by GGAlanSmithee** [comment]
@Bobgy 

Thanks for your contribution. I do not have the capacity (time and knowhow) to provide any meaningful feedback regarding your implementation, but I can tell you put some time into this PR, so wanted to tell you that your effort is appreciated, thanks!

@NekR could we give some feedback to let @Bobgy know if this is a feature we are even interested in, to let him know if it's worth pursuing further?

**Comment by Bobgy** [comment]
Looks like maintainer doesn't have capacity to review this.

**Pull request closed without merging**
